// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4eA_cIenQzAcxJvV1QE0Xpl98MMNSyx8',
    appId: '1:846994147082:web:bb0ed5db0d03f1f5869cf3',
    messagingSenderId: '846994147082',
    projectId: 'retsept-app-db287',
    authDomain: 'retsept-app-db287.firebaseapp.com',
    storageBucket: 'retsept-app-db287.appspot.com',
    measurementId: 'G-4MNVQKL0FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDGJsVvy7szTGa8U1EhxZwY58zX9Y9wh4',
    appId: '1:846994147082:android:a93a6ec1b92135bc869cf3',
    messagingSenderId: '846994147082',
    projectId: 'retsept-app-db287',
    storageBucket: 'retsept-app-db287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA04SzyAdNx2TghA6p7EfxI_IPVGmT0o_c',
    appId: '1:846994147082:ios:2330e5e5f45b78bd869cf3',
    messagingSenderId: '846994147082',
    projectId: 'retsept-app-db287',
    storageBucket: 'retsept-app-db287.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
